---
output: github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# hamapi

This package is based on the Harvard Art Museum API.
(https://www.harvardartmuseums.org/collections/api)

It allows the user to receive a list of artwork information (title, object id, period, century, culture, division, corresponding website url, image url, classification, department) by specifying the classification of artworks the user interested in. 

Allows user to download image of artworks from get_artwork_info function(coming)

Allows user to obtain information about gallery in each floor of the museum.

Allows user to obtain the information of which gallery has most artwork collections.

(Please note that this package can only be downloaded to local folder and run the R project version. 

Please try download this package from https://github.com/MelodieYuxiuHe/HAM and use devtools::load_all()

I will keep updating. Thank you for your patience.: ))

Feel free to contact me at: yuxiu.he@yahoo.com regarding problems.

Enjoy your art journey! 
